---
title: "DS 6371 Spring 2020 Kaggle Project"
author: "Indy, Aurian, Suchismita"
date: "04/05/2020"
output: html_document
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(curl)

```



```{r}
kaggle_train_data <- read.csv("/Users/suchismitamoharana/Documents/house-prices-advanced-regression-techniques/train.csv")
kaggle_train_data_filtered <- kaggle_train_data[which(kaggle_train_data$Neighborhood == 'NAmes' | kaggle_train_data$Neighborhood == 'Edwards' | kaggle_train_data$Neighborhood == 'BrkSide' | kaggle_train_data$GrLivArea < 4000),]

kaggle_test_data <- read.csv("/Users/suchismitamoharana/Documents/house-prices-advanced-regression-techniques/test.csv")
kaggle_test_data_filtered <- kaggle_test_data[which(kaggle_test_data$Neighborhood == 'NAmes' | kaggle_test_data$Neighborhood == 'Edwards' | kaggle_test_data$Neighborhood == 'BrkSide'),]

names(kaggle_train_data)[44] = "FirstFlrSF"
names(kaggle_train_data)[45] = "SecondFlrSF"
names(kaggle_train_data)[70] = "ThreeSeasonPorcharea"

names(kaggle_train_data_filtered)[44] = "FirstFlrSF"
names(kaggle_train_data_filtered)[45] = "SecondFlrSF"
names(kaggle_train_data_filtered)[70] = "ThreeSeasonPorcharea"


names(kaggle_test_data)[44] = "FirstFlrSF"
names(kaggle_test_data)[45] = "SecondFlrSF"
names(kaggle_test_data)[70] = "ThreeSeasonPorcharea"

names(kaggle_test_data_filtered)[44] = "FirstFlrSF"
names(kaggle_test_data_filtered)[45] = "SecondFlrSF"
names(kaggle_test_data_filtered)[70] = "ThreeSeasonPorcharea"


kaggle_train_data$LogSalePrice = log(kaggle_train_data$SalePrice)


kaggle_train_data%>%
  select(SalePrice)%>%
  ggplot(aes(x=SalePrice))+
  geom_histogram(fill="grey80", col = "blue")+
  ggtitle("Histogram Distribution of Sale Price")

kaggle_train_data%>%
  select(LogSalePrice)%>%
  ggplot(aes(x=LogSalePrice))+
  geom_histogram(fill="grey80", col = "blue")+
  ggtitle("Histogram Distribution of Log Sale Price")
```


### Plots for Explanatory Variables vs Log Sale Price
```{r}
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(MSSubClass, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("MSSubClass") + ylab("Sale Price") 
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(MSZoning, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("MS Zoning") + ylab("Sale Price") 

#################
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(LotFrontage, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Lot Frontage") + ylab("Sale Price") 
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(LotArea, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("LotArea") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = LotFrontage, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("LotFrontage") + ylab("Sale Price")   
kaggle_train_data %>% ggplot(mapping = aes (x = LotArea, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("LotArea") + ylab("Sale Price")   
#################



kaggle_train_data %>% ggplot(mapping = aes (x = reorder(Street, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Street Type") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(Alley, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Type of Alley Access") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(LotShape, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Lot Shape") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(LandContour, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Land Contour") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(Utilities, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Utilities") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(LotConfig, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Lot Configuration") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(LandSlope, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("LandSlope") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(Neighborhood, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Neighborhood") + ylab("Sale Price")  + theme(axis.text.x = element_text(angle=45,hjust=1, size=8))
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(Condition1, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Condition1") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(Condition2, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Condition2") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(BldgType, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("BldgType") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(HouseStyle, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("HouseStyle") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(OverallQual, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Overall Quality") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(OverallCond, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Overall Condition") + ylab("Sale Price")  

#################
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(YearBuilt, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("YearBuilt") + ylab("Sale Price")  
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(YearRemodAdd, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("YearRemodAdd") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = YearBuilt, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("YearBuilt") + ylab("Sale Price")   
kaggle_train_data %>% ggplot(mapping = aes (x = YearRemodAdd, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("YearRemodAdd") + ylab("Sale Price")   
#################



kaggle_train_data %>% ggplot(mapping = aes (x = reorder(RoofStyle, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Roof Style") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(RoofMatl, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Roof Material") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(Exterior1st, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Exterior Material1") + ylab("Sale Price")  + theme(axis.text.x = element_text(angle=45,hjust=1, size=8))
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(Exterior2nd, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Exterior Material2") + ylab("Sale Price")  + theme(axis.text.x = element_text(angle=45,hjust=1, size=8))
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(MasVnrType, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Masonry veneer type") + ylab("Sale Price")  

#################
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(MasVnrArea, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("MasVnrArea") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = MasVnrArea, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("MasVnrArea") + ylab("Sale Price")   
#################


kaggle_train_data %>% ggplot(mapping = aes (x = reorder(ExterQual, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Exterior Quality") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(ExterCond, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Exterior Condition") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(Foundation, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Foundation ") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(BsmtQual, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Quality") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(BsmtCond, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Condition") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(BsmtExposure, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Exposure") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(BsmtFinType1, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Rating of basement finished area") + ylab("Sale Price")  


#################
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(BsmtFinSF1, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("BsmtFinSF1") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = BsmtFinSF1, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("BsmtFinSF1") + ylab("BsmtFinSF1") 
#################


kaggle_train_data %>% ggplot(mapping = aes (x = reorder(BsmtFinType2, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Condition") + ylab("Sale Price")  



#################
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(BsmtFinSF2, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Quality") + ylab("Sale Price")  
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(BsmtUnfSF, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Condition") + ylab("Sale Price")  
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(TotalBsmtSF, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Condition") + ylab("Sale Price") 
kaggle_train_data %>% ggplot(mapping = aes (x = BsmtFinSF2, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("BsmtFinSF2") + ylab("Sale Price")   
kaggle_train_data %>% ggplot(mapping = aes (x = BsmtUnfSF, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("BsmtUnfSF") + ylab("Sale Price")   
kaggle_train_data %>% ggplot(mapping = aes (x = TotalBsmtSF, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("TotalBsmtSF") + ylab("Sale Price")   
#################



kaggle_train_data %>% ggplot(mapping = aes (x = reorder(Heating, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Heating Type") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(HeatingQC, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Heating quality and condition") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(CentralAir, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("CentralAir") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(Electrical, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Electrical") + ylab("Sale Price")  


#################
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(1stFlrSF, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Condition") + ylab("Sale Price")  
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(2ndFlrSF, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Condition") + ylab("Sale Price")  
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(LowQualFinSF, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Low quality finished square feet") + ylab("Sale Price")  
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(GrLivArea, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Condition") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = FirstFlrSF, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("1stFlrSF") + ylab("Sale Price")   
kaggle_train_data %>% ggplot(mapping = aes (x = SecondFlrSF, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("2ndFlrSF") + ylab("Sale Price")   
kaggle_train_data %>% ggplot(mapping = aes (x = LowQualFinSF, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("LowQualFinSF") + ylab("Sale Price")   
kaggle_train_data %>% ggplot(mapping = aes (x = GrLivArea, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("GrLivArea") + ylab("Sale Price")   
#################




kaggle_train_data %>% ggplot(mapping = aes (x = reorder(BsmtFullBath, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement FullBath") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(BsmtHalfBath, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement HalfBath") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(FullBath, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("FullBath") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(HalfBath, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("HalfBath") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(BedroomAbvGr, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Bedroom Above Grade") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(KitchenAbvGr, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Kitchen Above Grade") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(KitchenQual, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("KItchen Quality") + ylab("Sale Price")  

#################
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(TotRmsAbvGrd, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Quality") + ylab("Sale Price") 
kaggle_train_data %>% ggplot(mapping = aes (x = TotRmsAbvGrd, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("TotRmsAbvGrd") + ylab("Sale Price")   
#################

kaggle_train_data %>% ggplot(mapping = aes (x = reorder(Functional, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Functional") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(Fireplaces, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Fireplaces") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(FireplaceQu, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Fireplaces Quality") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(GarageType, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("GarageType") + ylab("Sale Price")  



#################
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(GarageYrBlt, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Condition") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = GarageYrBlt, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("GarageYrBlt") + ylab("Sale Price")   
#################

kaggle_train_data %>% ggplot(mapping = aes (x = reorder(GarageFinish, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("GarageFinish") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(GarageCars, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("GarageCars") + ylab("Sale Price")  


#################
#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(GarageArea, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Condition") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = GarageArea, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("GarageArea") + ylab("Sale Price")   
#################


kaggle_train_data %>% ggplot(mapping = aes (x = reorder(GarageQual, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Garage Quality") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(GarageCond, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Garage Condition") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(PavedDrive, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("PavedDrive") + ylab("Sale Price")  


#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(WoodDeckSF, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("WoodDeckSF") + ylab("Sale Price") 
kaggle_train_data %>% ggplot(mapping = aes (x = WoodDeckSF, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("WoodDeckSF") + ylab("Sale Price")   

#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(OpenPorchSF, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Condition") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = OpenPorchSF, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("OpenPorchSF") + ylab("Sale Price")   

#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(EnclosedPorch, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("EnclosedPorch") + ylab("Sale Price") 
kaggle_train_data %>% ggplot(mapping = aes (x = EnclosedPorch, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("EnclosedPorch") + ylab("Sale Price")   

#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(ThreeSeasonPorcharea, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("ThreeSeasonPorcharea") + ylab("Sale Price") 
kaggle_train_data %>% ggplot(mapping = aes (x = ThreeSeasonPorcharea, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("ThreeSeasonPorcharea") + ylab("Sale Price")   


#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(ScreenPorch, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Condition") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = ScreenPorch, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("ScreenPorch") + ylab("Sale Price")   

#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(PoolArea, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Basement Condition") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = PoolArea, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("PoolArea") + ylab("Sale Price")   

kaggle_train_data %>% ggplot(mapping = aes (x = reorder(PoolQC, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("PoolQC") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(Fence, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Fence") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(MiscFeature, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("MiscFeature") + ylab("Sale Price")  

#kaggle_train_data %>% ggplot(mapping = aes (x = reorder(MiscVal, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("MiscVal") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = MiscVal, y = LogSalePrice) ) + geom_point(colour = "blue") + xlab("MiscVal") + ylab("Sale Price")   


kaggle_train_data %>% ggplot(mapping = aes (x = reorder(MoSold, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("MoSold") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(YrSold, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("YrSold") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(SaleType, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("SaleType") + ylab("Sale Price")  
kaggle_train_data %>% ggplot(mapping = aes (x = reorder(SaleCondition, LogSalePrice),  y = LogSalePrice)) + geom_boxplot(fill = "grey80", colour = "blue") + xlab("Sale Condition") + ylab("Sale Price")  

```

